#alias make="make -j `distcc -j` CC=distcc"
#alias gvim="gvim --remote-silent"
alias tmux="tmux -2"
alias screen="tmux"
alias nano="vim"
#alias sudo="sudo MYVIMRC=$HOME/.vimrc"
#alias rm="gvfs-trash"
alias term="gnome-terminal"
alias open="xdg-open"
alias hamster='hamster-cli'
