--- 
:editor: /usr/bin/vim -f -c 'setlocal spell spelllang=en_us' -c 'set filetype=mail'
:thread_by_subject: false
:edit_signature: false
:ask_for_from: false
:ask_for_to: true
:ask_for_cc: true
:ask_for_bcc: false
:ask_for_subject: true
:account_selector: true
:confirm_no_attachments: true
:confirm_top_posting: true
:jump_to_open_message: true
:discard_snippets_from_encrypted_messages: false
:load_more_threads_when_scrolling: true
:default_attachment_save_dir: ""
:sent_source: maildir:/home/leon/Maildir/.Sent
:archive_sent: true
:poll_interval: 300
:wrap_width: 0
:slip_rows: 0
:col_jump: 2
:stem_language: english
:accounts:
  :default:
    :name: Leon Bogaert
    :email: leon@tim-online.nl
    :alternates: []

    :sendmail: /usr/sbin/sendmail -oem -ti
    :signature: /home/leon/.signature
    :gpgkey: ""
