---
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/leon/Maildir
  usual: true
  archived: false
  sync_back: true
  id: 1
  labels: []

- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/leon/Maildir/.Sent
  usual: true
  archived: true
  sync_back: true
  id: 2
  labels: []
