; ordered
(load "config/package")
(load "config/term")
(load "config/progmodes")
(load "config/general")
(load "config/evil")
; (load "config/keybindings")
; (load "config/custom")

; unordered
; (load "config/bookmarks")
; (load "config/enumerate-rectangle")
; (load "config/hideshow")
; ;(load "config/misc")
; (load "config/modes")
; (load "config/mouse")
; (load "config/org")
; (load "config/planner")
; (load "config/recentf")
; (load "config/smex")
; (load "config/magit")
; ;(load "config/graveyard")
; ;(load "config/theme")
